include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = garbagecollector

ADDITIONAL_INCLUDE_DIRS += \
        -I../basekit 

garbagecollector_C_FILES = \
	Collector.c \
	CollectorMarker.c 

include $(GNUSTEP_MAKEFILES)/subproject.make

