include $(GNUSTEP_MAKEFILES)/common.make

-include GNUmakefile.preamble
ifeq ($(steptalk), yes)
  include GNUmakefile.steptalk
endif
include GNUmakefile.tool
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble

