include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = thread

ADDITIONAL_INCLUDE_DIRS += \
        -I../basekit

thread_C_FILES = \
	Thread.c \
	ThreadMutex.c

include $(GNUSTEP_MAKEFILES)/subproject.make

