include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = base

base_C_FILES = \
	BStream.c \
	BStreamTag.c \
	ByteArray.c \
	Common.c \
	Date.c \
	Datum.c \
	Duration.c \
	DynLib.c \
	Hash.c \
	MainArgs.c \
	List.c \
	PHash.c \
	PortableGettimeofday.c \
	PortableSnprintf.c \
	PortableStrlcpy.c \
	PortableStrptime.c \
	PortableTruncate.c \
	PortableUsleep.c \
	RandomGen.c \
	Sorting.c \
	Stack.c \
	UTinstant.c \
	UTzones.c 

include $(GNUSTEP_MAKEFILES)/subproject.make

