#include "IoState.h"
#include "IoObject.h"

IoObject *IoVector_proto(void *state);
IoObject *IoBox_proto(void *state);

void IoAAVectorInit(IoState *self, IoObject *context)
{
	IoObject_setSlot_to_(context, SIOSYMBOL("Vector"), IoVector_proto(self));
	IoObject_setSlot_to_(context, SIOSYMBOL("Box"), IoBox_proto(self));
  {
  char *s = "Point := Vector clone setSize(2) \n"
	"Color := Vector clone setSize(4)\n"
	"Box copy := method(box,\n"
	"    self origin copy(box origin)\n"
	"    self size copy(box size)\n"
	")\n"
	"Sequence asVector := method(Vector clone copy(self))\n"
	"vector := method(\n"
	"\tv := Vector clone setSize(0)\n"
	"\tcall message arguments foreach(i, arg, \n"
	"\t\tv atPut(i, call sender doMessage(arg))\n"
	"\t)\n"
	"\tv\n"
	")\n"
	"Vector do(\n"
	"\tasString := method(self serialized asString)\n"
	"\t\n"
	"\tserialized := method(b, \n"
	"\t\tif(b == nil, b := Sequence clone)\n"
	"\t\tb appendSeq(\"vector(\")\n"
	"\t\tif(size > 0,\n"
	"\t\t\tfor (i, 0, size - 1,\n"
	"\t\t\t\tif(i > 0, b appendSeq(\", \"))\n"
	"\t\t\t\tb appendSeq(self at(i) asString)\n"
	"\t\t\t)\n"
	"\t\t)\n"
	"\t\tb appendSeq(\")\")\n"
	"\t)\n"
	"\tasSimpleString := method(\n"
	"\t\tresult := Sequence clone appendSeq(\"vector(\")\n"
	"\t\tif(size > 0,\n"
	"\t\t\tvalues := result\n"
	"\t\t\tfor(i, 0, size - 1,\n"
	"\t\t\t\tif(i > 0, values appendSeq(\", \"))\n"
	"\t\t\t\tvalues appendSeq(self at(i) asString)\n"
	"\t\t\t\tif(values == result and values size > 30,\n"
	"\t\t\t\t\tvalues := Sequence clone\n"
	"\t\t\t\t)\n"
	"\t\t\t)\n"
	"\t\t\tif(values != result,\n"
	"\t\t\t\tif(values size <= 10,\n"
	"\t\t\t\t\tresult appendSeq(values)\n"
	"\t\t\t\t,\n"
	"\t\t\t\t\tresult appendSeq(\", ...\")\n"
	"\t\t\t\t)\n"
	"\t\t\t)\n"
	"\t\t)\n"
	"\t\tresult appendSeq(\")\")\n"
	"\t)\n"
	"\tprint := method(self serialized print)\n"
	")\n"
	"Box do(\n"
	"\tasString := method(self serialized asString)\n"
	"\t\n"
	"\tserialized := method(b, \n"
	"\t\tif(b == nil, b := Sequence clone)\n"
	"\t\tb appendSeq(\"Box clone do(\")\n"
	"\t\tb appendSeq(\"setOrigin(\")\n"
	"\t\torigin serialized(b)\n"
	"\t\tb appendSeq(\"); \")\n"
	"\t\tb appendSeq(\"setSize(\")\n"
	"\t\tsize serialized(b)\n"
	"\t\tb appendSeq(\"));\")\n"
	"\t)\n"
	"\tprint := method(self serialized print)\n"
	")\n";
  IoState_on_doCString_withLabel_(self, context, s, "Vector.io");
  }

}
